-- 1. SECURITY: Admin Check Function
-- Truly secure check: queries the 'profiles' table for the 'admin' role.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
DECLARE
  current_role text;
BEGIN
  -- Check if user is authenticated
  IF auth.uid() IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Get the role from profiles
  SELECT role INTO current_role
  FROM public.profiles
  WHERE id = auth.uid();

  RETURN current_role = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. STORAGE: Create Private Buckets
-- We insert directly into storage.buckets. 
-- 'public' = false means files are NOT accessible via public URL.
INSERT INTO storage.buckets (id, name, public)
VALUES 
  ('academy_content', 'academy_content', false),
  ('agency_deliverables', 'agency_deliverables', false)
ON CONFLICT (id) DO NOTHING;

-- 3. STORAGE: Policies (The "Iron Dome")
-- We allow access ONLY to Admins. 
-- Students/Clients will access files via Signed URLs generated by the Server (which has admin rights).
-- This prevents anyone from scraping the bucket content directly.

-- Policy for Academy Content
CREATE POLICY "Admins can do everything on academy_content"
ON storage.objects
FOR ALL
USING (
  bucket_id = 'academy_content' 
  AND public.is_admin()
)
WITH CHECK (
  bucket_id = 'academy_content' 
  AND public.is_admin()
);

-- Policy for Agency Deliverables
CREATE POLICY "Admins can do everything on agency_deliverables"
ON storage.objects
FOR ALL
USING (
  bucket_id = 'agency_deliverables' 
  AND public.is_admin()
)
WITH CHECK (
  bucket_id = 'agency_deliverables' 
  AND public.is_admin()
);

-- 4. BONUS: Promote User to Admin (For Development)
-- Replace with your email to grant yourself the 'admin' role immediately.
UPDATE public.profiles
SET role = 'admin'
WHERE email = 'contactadjara@gmail.com'; -- Replace with your actual email if different
